version: '3.9'

services:
  api:
    container_name: nest_api
    build:
      dockerfile: Dockerfile
    ports:
    - ${SERVER_PORT}:3000
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:${DATABASE_VERSION}
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./pgdata/db:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .env